language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - python setup.py -q install
  - pip install -U pylint
  - pip install -U pytest
script:
  - python setup.py test
  - pylint comment_parser